<?php

/**
 * @file
 * Contains social_custom_settings.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_custom_settings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the social_custom_settings module.
    case 'help.page.social_custom_settings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My custom settings / modifications for Open Social') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_element_info_alter().
 */
function social_custom_settings_element_info_alter(array &$info) {
  if (isset($info['text_format']['#process'])) {
    $info['text_format']['#process'][] = 'social_custom_settings_filter_process_format';
  }
}

/**
* Readd ability of selecting format
 */
function social_custom_settings_filter_process_format($element) {

  // Only fields listed here will have text format settings disabled
  $full_html_field_ids = [
    'edit-body-0',
    'edit-field-profile-self-introduction-0',
    'edit-field-group-description-0'
  ];

  $full_html = FilterFormat::load('advanced_editor');
  $permission_name = $full_html->getPermissionName();
  $account = \Drupal::currentUser();

  if ($element['#type'] == 'text_format' && $account->hasPermission($permission_name) && in_array($element['#id'], $full_html_field_ids)) {
    $element['#format'] = 'advanced_editor';
    $element['format']['format']['#access'] = TRUE;
    $element['format']['format']['#value'] = 'advanced_editor';
    $element['format']['help']['#access'] = FALSE;
    $element['format']['format']['#options'] = ['advanced_editor' => 'Advanced Editor'];
  }

  return $element;
}